import { useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Warning } from '@phosphor-icons/react'
import { supabase } from '@/lib/supabase'
import { queryKeys } from '@/lib/queryKeys'
import { useOrganization } from '@/app/providers/OrganizationProvider'
import type { AccountingEntry } from '@/lib/database.types'
import { PageHeader, Skeleton } from '@ds'
import { AccountingEntryFormContent } from './AccountingEntryFormContent'

export function EditEntryPage() {
  const { t } = useTranslation('pages')
  const { entryId } = useParams<{ entryId: string }>()
  const navigate = useNavigate()
  const { currentOrg } = useOrganization()

  const {
    data: entry,
    isLoading,
    isError,
  } = useQuery({
    queryKey: queryKeys.accounting.detail(currentOrg?.id ?? '', entryId ?? ''),
    queryFn: async () => {
      if (!entryId) throw new Error('No entry ID')
      const { data, error } = await supabase
        .from('accounting_entries')
        .select('*')
        .eq('id', entryId)
        .single()
      if (error) throw error
      return data as AccountingEntry
    },
    enabled: !!entryId && !!currentOrg,
  })

  const isAutoGenerated = entry?.source_type != null && entry.source_type !== 'manual_import'

  const handleDone = () => navigate('/accounting')

  const backCrumb = (
    <button
      onClick={handleDone}
      className="mb-3 flex items-center gap-1.5 text-xs text-black/40 transition-colors hover:text-black/70"
    >
      <ArrowLeft size={13} weight="bold" />
      <span>{t('accounting.title')}</span>
    </button>
  )

  if (isLoading) {
    return (
      <div className="space-y-lg">
        <div>
          {backCrumb}
          <Skeleton className="mb-1 h-6 w-48 rounded" />
          <Skeleton className="h-4 w-64 rounded" />
        </div>
        <Skeleton className="h-64 w-full rounded-xl" />
      </div>
    )
  }

  if (isError || !entry) {
    return (
      <div className="space-y-lg">
        <div>
          {backCrumb}
          <PageHeader
            title={t('accounting.editEntry')}
            subtitle={t('accounting.editEntrySubtitle', 'Update accounting entry details')}
          />
        </div>
        <div className="flex flex-col items-center justify-center py-20">
          <p className="text-sm text-black/50">
            {t('accounting.entryNotFound', 'Entry not found')}
          </p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-lg">
      <div>
        {backCrumb}
        <PageHeader
          title={t('accounting.editEntry')}
          subtitle={t('accounting.editEntrySubtitle', 'Update accounting entry details')}
        />
      </div>

      {isAutoGenerated && (
        <div className="flex items-center gap-2.5 rounded-xl border border-amber-300/60 bg-amber-50 px-4 py-3 dark:border-amber-500/30 dark:bg-amber-900/20">
          <Warning size={18} weight="fill" className="shrink-0 text-amber-600" />
          <p className="text-sm text-amber-800 dark:text-amber-200">
            {t(
              'accounting.autoGenWarning',
              'This entry was auto-generated. Editing may cause inconsistencies.',
            )}
          </p>
        </div>
      )}

      <AccountingEntryFormContent entry={entry} onDone={handleDone} />
    </div>
  )
}
